/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.uti.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.SOFPA.uti.logic.dto.UTIDTO;
import co.edu.uniandes.csw.SOFPA.uti.logic.api.IUTILogicService;
import co.edu.uniandes.csw.SOFPA.uti.master.logic.api._IUTIMasterLogicService;
import co.edu.uniandes.csw.SOFPA.uti.master.logic.dto.UTIMasterDTO;
import co.edu.uniandes.csw.SOFPA.opinion.logic.api.IOpinionLogicService;
import co.edu.uniandes.csw.SOFPA.usuario.logic.api.IUsuarioLogicService;
import co.edu.uniandes.csw.SOFPA.opinion.logic.dto.OpinionDTO;
import co.edu.uniandes.csw.SOFPA.usuario.logic.dto.UsuarioDTO;
import javax.inject.Inject;


public abstract class _UTIMasterMockLogicService implements _IUTIMasterLogicService {

    protected static ArrayList<UTIMasterDTO> uTIMasterDtosList = new ArrayList<UTIMasterDTO>() ;
    @Inject
    protected IOpinionLogicService opinionPersistance;
    @Inject
    protected IUsuarioLogicService usuarioPersistance;
    @Inject
    protected IUTILogicService uTIPersistance;

    public UTIMasterDTO createMasterUTI(UTIMasterDTO uTI) {

        uTIPersistance.createUTI(uTI.getUTIEntity());
        for (OpinionDTO dto : uTI.getCreateopinion()) {
            opinionPersistance.createOpinion(dto);
        }
        for (UsuarioDTO dto : uTI.getCreateusuario()) {
            usuarioPersistance.createUsuario(dto);
        }
        uTIMasterDtosList.add(uTI);
        return uTI;
    }

    public UTIMasterDTO getMasterUTI(Long id) {
        for (UTIMasterDTO uTIMasterDTO : uTIMasterDtosList) {
            if (uTIMasterDTO.getUTIEntity().getId() == id) {
                return uTIMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterUTI(Long id) {
        for (UTIMasterDTO uTIMasterDTO : uTIMasterDtosList) {
            if (uTIMasterDTO.getUTIEntity().getId() == id) {

                for (OpinionDTO dto : uTIMasterDTO.getCreateopinion()) {
                    opinionPersistance.deleteOpinion(dto.getId());
                }
                uTIPersistance.deleteUTI(uTIMasterDTO.getId());
                uTIMasterDtosList.remove(uTIMasterDTO);
                for (UsuarioDTO dto : uTIMasterDTO.getCreateusuario()) {
                    usuarioPersistance.deleteUsuario(dto.getId());
                }
                uTIPersistance.deleteUTI(uTIMasterDTO.getId());
                uTIMasterDtosList.remove(uTIMasterDTO);
            }
        }

    }

    public void updateMasterUTI(UTIMasterDTO uTI) {

        // update Opinion
        if (uTI.getUpdateopinion() != null) {
            for (OpinionDTO dto : uTI.getUpdateopinion()) {
                opinionPersistance.updateOpinion(dto);
            }
        }
        // persist new Opinion
        if (uTI.getCreateopinion() != null) {
            for (OpinionDTO dto : uTI.getCreateopinion()) {
                OpinionDTO persistedOpinionDTO = opinionPersistance.createOpinion(dto);
                dto = persistedOpinionDTO;
            }
        }
        // delete Opinion
        if (uTI.getDeleteopinion() != null) {
            for (OpinionDTO dto : uTI.getDeleteopinion()) {

                opinionPersistance.deleteOpinion(dto.getId());
            }
        }
        // update Usuario
        if (uTI.getUpdateusuario() != null) {
            for (UsuarioDTO dto : uTI.getUpdateusuario()) {
                usuarioPersistance.updateUsuario(dto);
            }
        }
        // persist new Usuario
        if (uTI.getCreateusuario() != null) {
            for (UsuarioDTO dto : uTI.getCreateusuario()) {
                UsuarioDTO persistedUsuarioDTO = usuarioPersistance.createUsuario(dto);
                dto = persistedUsuarioDTO;
            }
        }
        // delete Usuario
        if (uTI.getDeleteusuario() != null) {
            for (UsuarioDTO dto : uTI.getDeleteusuario()) {

                usuarioPersistance.deleteUsuario(dto.getId());
            }
        }
    }
}