/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.uti.logic.ejb;
import java.util.List;
import javax.inject.Inject;

import co.edu.uniandes.csw.SOFPA.uti.logic.dto.UTIDTO;
import co.edu.uniandes.csw.SOFPA.uti.logic.dto.UTIPageDTO;
import co.edu.uniandes.csw.SOFPA.uti.logic.api._IUTILogicService;
import co.edu.uniandes.csw.SOFPA.uti.persistence.api.IUTIPersistence;

public abstract class _UTILogicService implements _IUTILogicService {

	@Inject
	protected IUTIPersistence persistance;

	public UTIDTO createUTI(UTIDTO uTI){
		return persistance.createUTI( uTI); 
    }

	public List<UTIDTO> getUTIs(){
		return persistance.getUTIs(); 
	}

	public UTIPageDTO getUTIs(Integer page, Integer maxRecords){
		return persistance.getUTIs(page, maxRecords); 
	}

	public UTIDTO getUTI(Long id){
		return persistance.getUTI(id); 
	}

	public void deleteUTI(Long id){
	    persistance.deleteUTI(id); 
	}

	public void updateUTI(UTIDTO uTI){
	    persistance.updateUTI(uTI); 
	}	
}