/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.sugerencia.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.SOFPA.sugerencia.logic.dto.SugerenciaPageDTO;
import co.edu.uniandes.csw.SOFPA.sugerencia.logic.dto.SugerenciaDTO;
import co.edu.uniandes.csw.SOFPA.sugerencia.logic.api.ISugerenciaLogicService;
import co.edu.uniandes.csw.SOFPA.sugerencia.persistence.SugerenciaPersistence;
import co.edu.uniandes.csw.SOFPA.sugerencia.persistence.api.ISugerenciaPersistence;
import co.edu.uniandes.csw.SOFPA.sugerencia.persistence.entity.SugerenciaEntity;
import co.edu.uniandes.csw.SOFPA.sugerencia.persistence.converter.SugerenciaConverter;
import static co.edu.uniandes.csw.SOFPA.util._TestUtil.*;

@RunWith(Arquillian.class)
public class SugerenciaLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(SugerenciaLogicService.class.getPackage())
				.addPackage(ISugerenciaLogicService.class.getPackage())
				.addPackage(SugerenciaPersistence.class.getPackage())
				.addPackage(SugerenciaEntity.class.getPackage())
				.addPackage(ISugerenciaPersistence.class.getPackage())
                .addPackage(SugerenciaDTO.class.getPackage())
                .addPackage(SugerenciaConverter.class.getPackage())
                .addPackage(SugerenciaEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private ISugerenciaLogicService sugerenciaLogicService;
	
	@Inject
	private ISugerenciaPersistence sugerenciaPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<SugerenciaDTO> dtos=sugerenciaPersistence.getSugerencias();
		for(SugerenciaDTO dto:dtos){
			sugerenciaPersistence.deleteSugerencia(dto.getId());
		}
	}

	private List<SugerenciaDTO> data=new ArrayList<SugerenciaDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			SugerenciaDTO pdto=new SugerenciaDTO();
			pdto.setName(generateRandom(String.class));
			pdto.setObsevacion(generateRandom(String.class));
			pdto.setTema(generateRandom(String.class));
			pdto.setLogin(generateRandom(String.class));
			pdto.setCodigo(generateRandom(Integer.class));
			pdto.setCarrera(generateRandom(String.class));
			pdto=sugerenciaPersistence.createSugerencia(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createSugerenciaTest(){
		SugerenciaDTO ldto=new SugerenciaDTO();
		ldto.setName(generateRandom(String.class));
		ldto.setObsevacion(generateRandom(String.class));
		ldto.setTema(generateRandom(String.class));
		ldto.setLogin(generateRandom(String.class));
		ldto.setCodigo(generateRandom(Integer.class));
		ldto.setCarrera(generateRandom(String.class));
		
		
		SugerenciaDTO result=sugerenciaLogicService.createSugerencia(ldto);
		
		Assert.assertNotNull(result);
		
		SugerenciaDTO pdto=sugerenciaPersistence.getSugerencia(result.getId());
		
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getObsevacion(), pdto.getObsevacion());	
		Assert.assertEquals(ldto.getTema(), pdto.getTema());	
		Assert.assertEquals(ldto.getLogin(), pdto.getLogin());	
		Assert.assertEquals(ldto.getCodigo(), pdto.getCodigo());	
		Assert.assertEquals(ldto.getCarrera(), pdto.getCarrera());	
	}
	
	@Test
	public void getSugerenciasTest(){
		List<SugerenciaDTO> list=sugerenciaLogicService.getSugerencias();
		Assert.assertEquals(list.size(), data.size());
        for(SugerenciaDTO ldto:list){
        	boolean found=false;
            for(SugerenciaDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getSugerenciaTest(){
		SugerenciaDTO pdto=data.get(0);
		SugerenciaDTO ldto=sugerenciaLogicService.getSugerencia(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getObsevacion(), ldto.getObsevacion());
		Assert.assertEquals(pdto.getTema(), ldto.getTema());
		Assert.assertEquals(pdto.getLogin(), ldto.getLogin());
		Assert.assertEquals(pdto.getCodigo(), ldto.getCodigo());
		Assert.assertEquals(pdto.getCarrera(), ldto.getCarrera());
        
	}
	
	@Test
	public void deleteSugerenciaTest(){
		SugerenciaDTO pdto=data.get(0);
		sugerenciaLogicService.deleteSugerencia(pdto.getId());
        SugerenciaDTO deleted=sugerenciaPersistence.getSugerencia(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateSugerenciaTest(){
		SugerenciaDTO pdto=data.get(0);
		
		SugerenciaDTO ldto=new SugerenciaDTO();
		ldto.setId(pdto.getId());
		ldto.setName(generateRandom(String.class));
		ldto.setObsevacion(generateRandom(String.class));
		ldto.setTema(generateRandom(String.class));
		ldto.setLogin(generateRandom(String.class));
		ldto.setCodigo(generateRandom(Integer.class));
		ldto.setCarrera(generateRandom(String.class));
		
		
		sugerenciaLogicService.updateSugerencia(ldto);
		
		
		SugerenciaDTO resp=sugerenciaPersistence.getSugerencia(pdto.getId());
		
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getObsevacion(), resp.getObsevacion());	
		Assert.assertEquals(ldto.getTema(), resp.getTema());	
		Assert.assertEquals(ldto.getLogin(), resp.getLogin());	
		Assert.assertEquals(ldto.getCodigo(), resp.getCodigo());	
		Assert.assertEquals(ldto.getCarrera(), resp.getCarrera());	
	}
	
	@Test
	public void getSugerenciaPaginationTest(){
		
		SugerenciaPageDTO dto1=sugerenciaLogicService.getSugerencias(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		SugerenciaPageDTO dto2=sugerenciaLogicService.getSugerencias(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(SugerenciaDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(SugerenciaDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(SugerenciaDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(SugerenciaDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        SugerenciaPageDTO dto3=sugerenciaLogicService.getSugerencias(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(SugerenciaDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(SugerenciaDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}