/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.opinion.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.SOFPA.opinion.logic.dto.OpinionDTO;
import co.edu.uniandes.csw.SOFPA.opinion.logic.dto.OpinionPageDTO;
import co.edu.uniandes.csw.SOFPA.opinion.persistence.api._IOpinionPersistence;
import co.edu.uniandes.csw.SOFPA.opinion.persistence.converter.OpinionConverter;
import co.edu.uniandes.csw.SOFPA.opinion.persistence.entity.OpinionEntity;

public abstract class _OpinionPersistence implements _IOpinionPersistence {

  	@PersistenceContext(unitName="ClinicaDeProblemasPU")
 
	protected EntityManager entityManager;
	
	public OpinionDTO createOpinion(OpinionDTO opinion) {
		OpinionEntity entity=OpinionConverter.persistenceDTO2Entity(opinion);
		entityManager.persist(entity);
		return OpinionConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<OpinionDTO> getOpinions() {
		Query q = entityManager.createQuery("select u from OpinionEntity u");
		return OpinionConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public OpinionPageDTO getOpinions(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from OpinionEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from OpinionEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		OpinionPageDTO response = new OpinionPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(OpinionConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public OpinionDTO getOpinion(Long id) {
		return OpinionConverter.entity2PersistenceDTO(entityManager.find(OpinionEntity.class, id));
	}

	public void deleteOpinion(Long id) {
		OpinionEntity entity=entityManager.find(OpinionEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateOpinion(OpinionDTO detail) {
		OpinionEntity entity=entityManager.merge(OpinionConverter.persistenceDTO2Entity(detail));
		OpinionConverter.entity2PersistenceDTO(entity);
	}

}