/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.uti.master.persistence;
import co.edu.uniandes.csw.SOFPA.opinion.logic.dto.OpinionDTO;
import co.edu.uniandes.csw.SOFPA.uti.master.persistence.entity.UTIopinionEntity;
import co.edu.uniandes.csw.SOFPA.opinion.persistence.converter.OpinionConverter;
import co.edu.uniandes.csw.SOFPA.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.SOFPA.uti.master.persistence.entity.UTIusuarioEntity;
import co.edu.uniandes.csw.SOFPA.usuario.persistence.converter.UsuarioConverter;
import co.edu.uniandes.csw.SOFPA.uti.logic.dto.UTIDTO;
import co.edu.uniandes.csw.SOFPA.uti.master.logic.dto.UTIMasterDTO;
import co.edu.uniandes.csw.SOFPA.uti.master.persistence.api._IUTIMasterPersistence;
import co.edu.uniandes.csw.SOFPA.uti.persistence.api.IUTIPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _UTIMasterPersistence implements _IUTIMasterPersistence {

  	@PersistenceContext(unitName="ClinicaDeProblemasPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected IUTIPersistence utiPersistence;  

    public UTIMasterDTO getUTI(Long utiId) {
        UTIMasterDTO utiMasterDTO = new UTIMasterDTO();
        UTIDTO uti = utiPersistence.getUTI(utiId);
        utiMasterDTO.setUTIEntity(uti);
        utiMasterDTO.setListopinion(getUTIopinionEntityList(utiId));
        utiMasterDTO.setListusuario(getUTIusuarioEntityList(utiId));
        return utiMasterDTO;
    }

    public UTIopinionEntity createUTIopinionEntity(UTIopinionEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteUTIopinionEntity(Long uTIId, Long opinionId) {
        Query q = entityManager.createNamedQuery("UTIopinionEntity.deleteUTIopinionEntity");
        q.setParameter("uTIId", uTIId);
        q.setParameter("opinionId", opinionId);
        q.executeUpdate();
    }

    public List<OpinionDTO> getUTIopinionEntityList(Long uTIId) {
        ArrayList<OpinionDTO> resp = new ArrayList<OpinionDTO>();
        Query q = entityManager.createNamedQuery("UTIopinionEntity.getByMasterId");
        q.setParameter("uTIId",uTIId);
        List<UTIopinionEntity> qResult =  q.getResultList();
        for (UTIopinionEntity entity : qResult) { 
            if(entity.getOpinionIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(OpinionConverter.entity2PersistenceDTO(entity.getOpinionIdEntity()));
        }
        return resp;
    }
    public UTIusuarioEntity createUTIusuarioEntity(UTIusuarioEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteUTIusuarioEntity(Long uTIId, Long usuarioId) {
        Query q = entityManager.createNamedQuery("UTIusuarioEntity.deleteUTIusuarioEntity");
        q.setParameter("uTIId", uTIId);
        q.setParameter("usuarioId", usuarioId);
        q.executeUpdate();
    }

    public List<UsuarioDTO> getUTIusuarioEntityList(Long uTIId) {
        ArrayList<UsuarioDTO> resp = new ArrayList<UsuarioDTO>();
        Query q = entityManager.createNamedQuery("UTIusuarioEntity.getByMasterId");
        q.setParameter("uTIId",uTIId);
        List<UTIusuarioEntity> qResult =  q.getResultList();
        for (UTIusuarioEntity entity : qResult) { 
            if(entity.getUsuarioIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(UsuarioConverter.entity2PersistenceDTO(entity.getUsuarioIdEntity()));
        }
        return resp;
    }

}
