/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.usuario.master.logic.dto;

import co.edu.uniandes.csw.SOFPA.contacto.logic.dto.ContactoDTO;
import co.edu.uniandes.csw.SOFPA.recurso.logic.dto.RecursoDTO;
import co.edu.uniandes.csw.SOFPA.usuario.logic.dto.UsuarioDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _UsuarioMasterDTO {

 
    protected UsuarioDTO usuarioEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public UsuarioDTO getUsuarioEntity() {
        return usuarioEntity;
    }

    public void setUsuarioEntity(UsuarioDTO usuarioEntity) {
        this.usuarioEntity = usuarioEntity;
    }
    
    public List<ContactoDTO> createcontacto;
    public List<ContactoDTO> updatecontacto;
    public List<ContactoDTO> deletecontacto;
    public List<ContactoDTO> listcontacto;	
    public List<RecursoDTO> createrecurso;
    public List<RecursoDTO> updaterecurso;
    public List<RecursoDTO> deleterecurso;
    public List<RecursoDTO> listrecurso;	
	
	
	
    public List<ContactoDTO> getCreatecontacto(){ return createcontacto; };
    public void setCreatecontacto(List<ContactoDTO> createcontacto){ this.createcontacto=createcontacto; };
    public List<ContactoDTO> getUpdatecontacto(){ return updatecontacto; };
    public void setUpdatecontacto(List<ContactoDTO> updatecontacto){ this.updatecontacto=updatecontacto; };
    public List<ContactoDTO> getDeletecontacto(){ return deletecontacto; };
    public void setDeletecontacto(List<ContactoDTO> deletecontacto){ this.deletecontacto=deletecontacto; };
    public List<ContactoDTO> getListcontacto(){ return listcontacto; };
    public void setListcontacto(List<ContactoDTO> listcontacto){ this.listcontacto=listcontacto; };	
    public List<RecursoDTO> getCreaterecurso(){ return createrecurso; };
    public void setCreaterecurso(List<RecursoDTO> createrecurso){ this.createrecurso=createrecurso; };
    public List<RecursoDTO> getUpdaterecurso(){ return updaterecurso; };
    public void setUpdaterecurso(List<RecursoDTO> updaterecurso){ this.updaterecurso=updaterecurso; };
    public List<RecursoDTO> getDeleterecurso(){ return deleterecurso; };
    public void setDeleterecurso(List<RecursoDTO> deleterecurso){ this.deleterecurso=deleterecurso; };
    public List<RecursoDTO> getListrecurso(){ return listrecurso; };
    public void setListrecurso(List<RecursoDTO> listrecurso){ this.listrecurso=listrecurso; };	
	
	
}

