/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.opinion.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.SOFPA.opinion.logic.dto.OpinionPageDTO;
import co.edu.uniandes.csw.SOFPA.opinion.logic.dto.OpinionDTO;
import co.edu.uniandes.csw.SOFPA.opinion.logic.api.IOpinionLogicService;
import co.edu.uniandes.csw.SOFPA.opinion.persistence.OpinionPersistence;
import co.edu.uniandes.csw.SOFPA.opinion.persistence.api.IOpinionPersistence;
import co.edu.uniandes.csw.SOFPA.opinion.persistence.entity.OpinionEntity;
import co.edu.uniandes.csw.SOFPA.opinion.persistence.converter.OpinionConverter;
import static co.edu.uniandes.csw.SOFPA.util._TestUtil.*;

@RunWith(Arquillian.class)
public class OpinionLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(OpinionLogicService.class.getPackage())
				.addPackage(IOpinionLogicService.class.getPackage())
				.addPackage(OpinionPersistence.class.getPackage())
				.addPackage(OpinionEntity.class.getPackage())
				.addPackage(IOpinionPersistence.class.getPackage())
                .addPackage(OpinionDTO.class.getPackage())
                .addPackage(OpinionConverter.class.getPackage())
                .addPackage(OpinionEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IOpinionLogicService opinionLogicService;
	
	@Inject
	private IOpinionPersistence opinionPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<OpinionDTO> dtos=opinionPersistence.getOpinions();
		for(OpinionDTO dto:dtos){
			opinionPersistence.deleteOpinion(dto.getId());
		}
	}

	private List<OpinionDTO> data=new ArrayList<OpinionDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			OpinionDTO pdto=new OpinionDTO();
			pdto.setName(generateRandom(String.class));
			pdto.setContenido(generateRandom(String.class));
			pdto.setCalificacion(generateRandom(Integer.class));
			pdto.setDificultadEjercicios(generateRandom(String.class));
			pdto.setSolucionDudas(generateRandom(Integer.class));
			pdto.setFueDeAyuda(generateRandom(Boolean.class));
			pdto=opinionPersistence.createOpinion(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createOpinionTest(){
		OpinionDTO ldto=new OpinionDTO();
		ldto.setName(generateRandom(String.class));
		ldto.setContenido(generateRandom(String.class));
		ldto.setCalificacion(generateRandom(Integer.class));
		ldto.setDificultadEjercicios(generateRandom(String.class));
		ldto.setSolucionDudas(generateRandom(Integer.class));
		ldto.setFueDeAyuda(generateRandom(Boolean.class));
		
		
		OpinionDTO result=opinionLogicService.createOpinion(ldto);
		
		Assert.assertNotNull(result);
		
		OpinionDTO pdto=opinionPersistence.getOpinion(result.getId());
		
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getContenido(), pdto.getContenido());	
		Assert.assertEquals(ldto.getCalificacion(), pdto.getCalificacion());	
		Assert.assertEquals(ldto.getDificultadEjercicios(), pdto.getDificultadEjercicios());	
		Assert.assertEquals(ldto.getSolucionDudas(), pdto.getSolucionDudas());	
		Assert.assertEquals(ldto.getFueDeAyuda(), pdto.getFueDeAyuda());	
	}
	
	@Test
	public void getOpinionsTest(){
		List<OpinionDTO> list=opinionLogicService.getOpinions();
		Assert.assertEquals(list.size(), data.size());
        for(OpinionDTO ldto:list){
        	boolean found=false;
            for(OpinionDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getOpinionTest(){
		OpinionDTO pdto=data.get(0);
		OpinionDTO ldto=opinionLogicService.getOpinion(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getContenido(), ldto.getContenido());
		Assert.assertEquals(pdto.getCalificacion(), ldto.getCalificacion());
		Assert.assertEquals(pdto.getDificultadEjercicios(), ldto.getDificultadEjercicios());
		Assert.assertEquals(pdto.getSolucionDudas(), ldto.getSolucionDudas());
		Assert.assertEquals(pdto.getFueDeAyuda(), ldto.getFueDeAyuda());
        
	}
	
	@Test
	public void deleteOpinionTest(){
		OpinionDTO pdto=data.get(0);
		opinionLogicService.deleteOpinion(pdto.getId());
        OpinionDTO deleted=opinionPersistence.getOpinion(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateOpinionTest(){
		OpinionDTO pdto=data.get(0);
		
		OpinionDTO ldto=new OpinionDTO();
		ldto.setId(pdto.getId());
		ldto.setName(generateRandom(String.class));
		ldto.setContenido(generateRandom(String.class));
		ldto.setCalificacion(generateRandom(Integer.class));
		ldto.setDificultadEjercicios(generateRandom(String.class));
		ldto.setSolucionDudas(generateRandom(Integer.class));
		ldto.setFueDeAyuda(generateRandom(Boolean.class));
		
		
		opinionLogicService.updateOpinion(ldto);
		
		
		OpinionDTO resp=opinionPersistence.getOpinion(pdto.getId());
		
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getContenido(), resp.getContenido());	
		Assert.assertEquals(ldto.getCalificacion(), resp.getCalificacion());	
		Assert.assertEquals(ldto.getDificultadEjercicios(), resp.getDificultadEjercicios());	
		Assert.assertEquals(ldto.getSolucionDudas(), resp.getSolucionDudas());	
		Assert.assertEquals(ldto.getFueDeAyuda(), resp.getFueDeAyuda());	
	}
	
	@Test
	public void getOpinionPaginationTest(){
		
		OpinionPageDTO dto1=opinionLogicService.getOpinions(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		OpinionPageDTO dto2=opinionLogicService.getOpinions(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(OpinionDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(OpinionDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(OpinionDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(OpinionDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        OpinionPageDTO dto3=opinionLogicService.getOpinions(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(OpinionDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(OpinionDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}