/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.recurso.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.SOFPA.recurso.logic.dto.RecursoPageDTO;
import co.edu.uniandes.csw.SOFPA.recurso.logic.dto.RecursoDTO;
import co.edu.uniandes.csw.SOFPA.recurso.logic.api.IRecursoLogicService;
import co.edu.uniandes.csw.SOFPA.recurso.persistence.RecursoPersistence;
import co.edu.uniandes.csw.SOFPA.recurso.persistence.api.IRecursoPersistence;
import co.edu.uniandes.csw.SOFPA.recurso.persistence.entity.RecursoEntity;
import co.edu.uniandes.csw.SOFPA.recurso.persistence.converter.RecursoConverter;
import static co.edu.uniandes.csw.SOFPA.util._TestUtil.*;

@RunWith(Arquillian.class)
public class RecursoLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(RecursoLogicService.class.getPackage())
				.addPackage(IRecursoLogicService.class.getPackage())
				.addPackage(RecursoPersistence.class.getPackage())
				.addPackage(RecursoEntity.class.getPackage())
				.addPackage(IRecursoPersistence.class.getPackage())
                .addPackage(RecursoDTO.class.getPackage())
                .addPackage(RecursoConverter.class.getPackage())
                .addPackage(RecursoEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IRecursoLogicService recursoLogicService;
	
	@Inject
	private IRecursoPersistence recursoPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<RecursoDTO> dtos=recursoPersistence.getRecursos();
		for(RecursoDTO dto:dtos){
			recursoPersistence.deleteRecurso(dto.getId());
		}
	}

	private List<RecursoDTO> data=new ArrayList<RecursoDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			RecursoDTO pdto=new RecursoDTO();
			pdto.setName(generateRandom(String.class));
			pdto.setTema(generateRandom(String.class));
			pdto.setDificultad(generateRandom(String.class));
			pdto.setTipo(generateRandom(String.class));
			pdto.setAvalado(generateRandom(Boolean.class));
			pdto.setSemestre(generateRandom(Integer.class));
			pdto.setMateria(generateRandom(String.class));
			pdto.setUrl(generateRandom(String.class));
			pdto=recursoPersistence.createRecurso(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createRecursoTest(){
		RecursoDTO ldto=new RecursoDTO();
		ldto.setName(generateRandom(String.class));
		ldto.setTema(generateRandom(String.class));
		ldto.setDificultad(generateRandom(String.class));
		ldto.setTipo(generateRandom(String.class));
		ldto.setAvalado(generateRandom(Boolean.class));
		ldto.setSemestre(generateRandom(Integer.class));
		ldto.setMateria(generateRandom(String.class));
		ldto.setUrl(generateRandom(String.class));
		
		
		RecursoDTO result=recursoLogicService.createRecurso(ldto);
		
		Assert.assertNotNull(result);
		
		RecursoDTO pdto=recursoPersistence.getRecurso(result.getId());
		
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getTema(), pdto.getTema());	
		Assert.assertEquals(ldto.getDificultad(), pdto.getDificultad());	
		Assert.assertEquals(ldto.getTipo(), pdto.getTipo());	
		Assert.assertEquals(ldto.getAvalado(), pdto.getAvalado());	
		Assert.assertEquals(ldto.getSemestre(), pdto.getSemestre());	
		Assert.assertEquals(ldto.getMateria(), pdto.getMateria());	
		Assert.assertEquals(ldto.getUrl(), pdto.getUrl());	
	}
	
	@Test
	public void getRecursosTest(){
		List<RecursoDTO> list=recursoLogicService.getRecursos();
		Assert.assertEquals(list.size(), data.size());
        for(RecursoDTO ldto:list){
        	boolean found=false;
            for(RecursoDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getRecursoTest(){
		RecursoDTO pdto=data.get(0);
		RecursoDTO ldto=recursoLogicService.getRecurso(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getTema(), ldto.getTema());
		Assert.assertEquals(pdto.getDificultad(), ldto.getDificultad());
		Assert.assertEquals(pdto.getTipo(), ldto.getTipo());
		Assert.assertEquals(pdto.getAvalado(), ldto.getAvalado());
		Assert.assertEquals(pdto.getSemestre(), ldto.getSemestre());
		Assert.assertEquals(pdto.getMateria(), ldto.getMateria());
		Assert.assertEquals(pdto.getUrl(), ldto.getUrl());
        
	}
	
	@Test
	public void deleteRecursoTest(){
		RecursoDTO pdto=data.get(0);
		recursoLogicService.deleteRecurso(pdto.getId());
        RecursoDTO deleted=recursoPersistence.getRecurso(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateRecursoTest(){
		RecursoDTO pdto=data.get(0);
		
		RecursoDTO ldto=new RecursoDTO();
		ldto.setId(pdto.getId());
		ldto.setName(generateRandom(String.class));
		ldto.setTema(generateRandom(String.class));
		ldto.setDificultad(generateRandom(String.class));
		ldto.setTipo(generateRandom(String.class));
		ldto.setAvalado(generateRandom(Boolean.class));
		ldto.setSemestre(generateRandom(Integer.class));
		ldto.setMateria(generateRandom(String.class));
		ldto.setUrl(generateRandom(String.class));
		
		
		recursoLogicService.updateRecurso(ldto);
		
		
		RecursoDTO resp=recursoPersistence.getRecurso(pdto.getId());
		
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getTema(), resp.getTema());	
		Assert.assertEquals(ldto.getDificultad(), resp.getDificultad());	
		Assert.assertEquals(ldto.getTipo(), resp.getTipo());	
		Assert.assertEquals(ldto.getAvalado(), resp.getAvalado());	
		Assert.assertEquals(ldto.getSemestre(), resp.getSemestre());	
		Assert.assertEquals(ldto.getMateria(), resp.getMateria());	
		Assert.assertEquals(ldto.getUrl(), resp.getUrl());	
	}
	
	@Test
	public void getRecursoPaginationTest(){
		
		RecursoPageDTO dto1=recursoLogicService.getRecursos(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		RecursoPageDTO dto2=recursoLogicService.getRecursos(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(RecursoDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(RecursoDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(RecursoDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(RecursoDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        RecursoPageDTO dto3=recursoLogicService.getRecursos(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(RecursoDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(RecursoDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}