/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.usuario.master.logic.ejb;

import co.edu.uniandes.csw.SOFPA.contacto.logic.dto.ContactoDTO;
import co.edu.uniandes.csw.SOFPA.contacto.persistence.api.IContactoPersistence;
import co.edu.uniandes.csw.SOFPA.recurso.logic.dto.RecursoDTO;
import co.edu.uniandes.csw.SOFPA.recurso.persistence.api.IRecursoPersistence;
import co.edu.uniandes.csw.SOFPA.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.SOFPA.usuario.master.logic.api._IUsuarioMasterLogicService;
import co.edu.uniandes.csw.SOFPA.usuario.master.logic.dto.UsuarioMasterDTO;
import co.edu.uniandes.csw.SOFPA.usuario.master.persistence.api.IUsuarioMasterPersistence;
import co.edu.uniandes.csw.SOFPA.usuario.master.persistence.entity.UsuariocontactoEntity;
import co.edu.uniandes.csw.SOFPA.usuario.master.persistence.entity.UsuariorecursoEntity;
import co.edu.uniandes.csw.SOFPA.usuario.persistence.api.IUsuarioPersistence;
import javax.inject.Inject;

public abstract class _UsuarioMasterLogicService implements _IUsuarioMasterLogicService {

    @Inject
    protected IUsuarioPersistence usuarioPersistance;
    @Inject
    protected IUsuarioMasterPersistence usuarioMasterPersistance;
    @Inject
    protected IContactoPersistence contactoPersistance;
    @Inject
    protected IRecursoPersistence recursoPersistance;

    public UsuarioMasterDTO createMasterUsuario(UsuarioMasterDTO usuario) {
        UsuarioDTO persistedUsuarioDTO = usuarioPersistance.createUsuario(usuario.getUsuarioEntity());
        if (usuario.getCreatecontacto() != null) {
            for (ContactoDTO contactoDTO : usuario.getCreatecontacto()) {
                ContactoDTO createdContactoDTO = contactoPersistance.createContacto(contactoDTO);
                UsuariocontactoEntity usuarioContactoEntity = new UsuariocontactoEntity(persistedUsuarioDTO.getId(), createdContactoDTO.getId());
                usuarioMasterPersistance.createUsuariocontactoEntity(usuarioContactoEntity);
            }
        }
        if (usuario.getCreaterecurso() != null) {
            for (RecursoDTO recursoDTO : usuario.getCreaterecurso()) {
                RecursoDTO createdRecursoDTO = recursoPersistance.createRecurso(recursoDTO);
                UsuariorecursoEntity usuarioRecursoEntity = new UsuariorecursoEntity(persistedUsuarioDTO.getId(), createdRecursoDTO.getId());
                usuarioMasterPersistance.createUsuariorecursoEntity(usuarioRecursoEntity);
            }
        }
        // update contacto
        if (usuario.getUpdatecontacto() != null) {
            for (ContactoDTO contactoDTO : usuario.getUpdatecontacto()) {
                contactoPersistance.updateContacto(contactoDTO);
                UsuariocontactoEntity usuarioContactoEntity = new UsuariocontactoEntity(persistedUsuarioDTO.getId(), contactoDTO.getId());
                usuarioMasterPersistance.createUsuariocontactoEntity(usuarioContactoEntity);
            }
        }
        // update recurso
        if (usuario.getUpdaterecurso() != null) {
            for (RecursoDTO recursoDTO : usuario.getUpdaterecurso()) {
                recursoPersistance.updateRecurso(recursoDTO);
                UsuariorecursoEntity usuarioRecursoEntity = new UsuariorecursoEntity(persistedUsuarioDTO.getId(), recursoDTO.getId());
                usuarioMasterPersistance.createUsuariorecursoEntity(usuarioRecursoEntity);
            }
        }
        return usuario;
    }

    public UsuarioMasterDTO getMasterUsuario(Long id) {
        return usuarioMasterPersistance.getUsuario(id);
    }

    public void deleteMasterUsuario(Long id) {
        usuarioPersistance.deleteUsuario(id);
    }

    public void updateMasterUsuario(UsuarioMasterDTO usuario) {
        usuarioPersistance.updateUsuario(usuario.getUsuarioEntity());

        //---- FOR RELATIONSHIP
        // persist new contacto
        if (usuario.getCreatecontacto() != null) {
            for (ContactoDTO contactoDTO : usuario.getCreatecontacto()) {
                ContactoDTO createdContactoDTO = contactoPersistance.createContacto(contactoDTO);
                UsuariocontactoEntity usuarioContactoEntity = new UsuariocontactoEntity(usuario.getUsuarioEntity().getId(), createdContactoDTO.getId());
                usuarioMasterPersistance.createUsuariocontactoEntity(usuarioContactoEntity);
            }
        }
        // update contacto
        if (usuario.getUpdatecontacto() != null) {
            for (ContactoDTO contactoDTO : usuario.getUpdatecontacto()) {
                contactoPersistance.updateContacto(contactoDTO);
            }
        }
        // delete contacto
        if (usuario.getDeletecontacto() != null) {
            for (ContactoDTO contactoDTO : usuario.getDeletecontacto()) {
                usuarioMasterPersistance.deleteUsuariocontactoEntity(usuario.getUsuarioEntity().getId(), contactoDTO.getId());
                contactoPersistance.deleteContacto(contactoDTO.getId());
            }
        }
        // delete recurso
        if (usuario.getDeleterecurso() != null) {
            for (RecursoDTO recursoDTO : usuario.getDeleterecurso()) {
                usuarioMasterPersistance.deleteUsuariorecursoEntity(usuario.getUsuarioEntity().getId(), recursoDTO.getId());
            }
        }
        // persist new recurso
        if (usuario.getCreaterecurso() != null) {
            for (RecursoDTO recursoDTO : usuario.getCreaterecurso()) {
                UsuariorecursoEntity usuarioRecursoEntity = new UsuariorecursoEntity(usuario.getUsuarioEntity().getId(), recursoDTO.getId());
                usuarioMasterPersistance.createUsuariorecursoEntity(usuarioRecursoEntity);
            }
        }
        // update recurso
        if (usuario.getUpdaterecurso() != null) {
            for (RecursoDTO recursoDTO : usuario.getUpdaterecurso()) {
                usuarioMasterPersistance.deleteUsuariorecursoEntity(usuario.getUsuarioEntity().getId(), recursoDTO.getId());
                recursoPersistance.updateRecurso(recursoDTO);
                UsuariorecursoEntity usuarioRecursoEntity = new UsuariorecursoEntity(usuario.getId(), recursoDTO.getId());
                usuarioMasterPersistance.createUsuariorecursoEntity(usuarioRecursoEntity);
                
            }
        }
    }
}
