/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.usuario.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.SOFPA.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.SOFPA.usuario.logic.api.IUsuarioLogicService;
import co.edu.uniandes.csw.SOFPA.usuario.master.logic.api._IUsuarioMasterLogicService;
import co.edu.uniandes.csw.SOFPA.usuario.master.logic.dto.UsuarioMasterDTO;
import co.edu.uniandes.csw.SOFPA.contacto.logic.api.IContactoLogicService;
import co.edu.uniandes.csw.SOFPA.recurso.logic.api.IRecursoLogicService;
import co.edu.uniandes.csw.SOFPA.contacto.logic.dto.ContactoDTO;
import co.edu.uniandes.csw.SOFPA.recurso.logic.dto.RecursoDTO;
import javax.inject.Inject;


public abstract class _UsuarioMasterMockLogicService implements _IUsuarioMasterLogicService {

    protected static ArrayList<UsuarioMasterDTO> usuarioMasterDtosList = new ArrayList<UsuarioMasterDTO>() ;
    @Inject
    protected IContactoLogicService contactoPersistance;
    @Inject
    protected IRecursoLogicService recursoPersistance;
    @Inject
    protected IUsuarioLogicService usuarioPersistance;

    public UsuarioMasterDTO createMasterUsuario(UsuarioMasterDTO usuario) {

        usuarioPersistance.createUsuario(usuario.getUsuarioEntity());
        for (ContactoDTO dto : usuario.getCreatecontacto()) {
            contactoPersistance.createContacto(dto);
        }
        for (RecursoDTO dto : usuario.getCreaterecurso()) {
            recursoPersistance.createRecurso(dto);
        }
        usuarioMasterDtosList.add(usuario);
        return usuario;
    }

    public UsuarioMasterDTO getMasterUsuario(Long id) {
        for (UsuarioMasterDTO usuarioMasterDTO : usuarioMasterDtosList) {
            if (usuarioMasterDTO.getUsuarioEntity().getId() == id) {
                return usuarioMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterUsuario(Long id) {
        for (UsuarioMasterDTO usuarioMasterDTO : usuarioMasterDtosList) {
            if (usuarioMasterDTO.getUsuarioEntity().getId() == id) {

                for (ContactoDTO dto : usuarioMasterDTO.getCreatecontacto()) {
                    contactoPersistance.deleteContacto(dto.getId());
                }
                usuarioPersistance.deleteUsuario(usuarioMasterDTO.getId());
                usuarioMasterDtosList.remove(usuarioMasterDTO);
                for (RecursoDTO dto : usuarioMasterDTO.getCreaterecurso()) {
                    recursoPersistance.deleteRecurso(dto.getId());
                }
                usuarioPersistance.deleteUsuario(usuarioMasterDTO.getId());
                usuarioMasterDtosList.remove(usuarioMasterDTO);
            }
        }

    }

    public void updateMasterUsuario(UsuarioMasterDTO usuario) {

        // update Contacto
        if (usuario.getUpdatecontacto() != null) {
            for (ContactoDTO dto : usuario.getUpdatecontacto()) {
                contactoPersistance.updateContacto(dto);
            }
        }
        // persist new Contacto
        if (usuario.getCreatecontacto() != null) {
            for (ContactoDTO dto : usuario.getCreatecontacto()) {
                ContactoDTO persistedContactoDTO = contactoPersistance.createContacto(dto);
                dto = persistedContactoDTO;
            }
        }
        // delete Contacto
        if (usuario.getDeletecontacto() != null) {
            for (ContactoDTO dto : usuario.getDeletecontacto()) {

                contactoPersistance.deleteContacto(dto.getId());
            }
        }
        // update Recurso
        if (usuario.getUpdaterecurso() != null) {
            for (RecursoDTO dto : usuario.getUpdaterecurso()) {
                recursoPersistance.updateRecurso(dto);
            }
        }
        // persist new Recurso
        if (usuario.getCreaterecurso() != null) {
            for (RecursoDTO dto : usuario.getCreaterecurso()) {
                RecursoDTO persistedRecursoDTO = recursoPersistance.createRecurso(dto);
                dto = persistedRecursoDTO;
            }
        }
        // delete Recurso
        if (usuario.getDeleterecurso() != null) {
            for (RecursoDTO dto : usuario.getDeleterecurso()) {

                recursoPersistance.deleteRecurso(dto.getId());
            }
        }
    }
}