/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.uti.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.SOFPA.uti.logic.dto.UTIPageDTO;
import co.edu.uniandes.csw.SOFPA.uti.logic.dto.UTIDTO;
import co.edu.uniandes.csw.SOFPA.uti.persistence.api.IUTIPersistence;
import co.edu.uniandes.csw.SOFPA.uti.persistence.entity.UTIEntity;
import co.edu.uniandes.csw.SOFPA.uti.persistence.converter.UTIConverter;
import static co.edu.uniandes.csw.SOFPA.util._TestUtil.*;

@RunWith(Arquillian.class)
public class UTIPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(UTIPersistence.class.getPackage())
				.addPackage(UTIEntity.class.getPackage())
				.addPackage(IUTIPersistence.class.getPackage())
                .addPackage(UTIDTO.class.getPackage())
                .addPackage(UTIConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IUTIPersistence uTIPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from UTIEntity").executeUpdate();
	}

	private List<UTIEntity> data=new ArrayList<UTIEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			UTIEntity entity=new UTIEntity();
			entity.setName(generateRandom(String.class));
			entity.setFechaEvento(generateRandom(Date.class));
			entity.setSalon(generateRandom(String.class));
			entity.setMateria(generateRandom(String.class));
			entity.setInformacion(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createUTITest(){
		UTIDTO dto=new UTIDTO();
		dto.setName(generateRandom(String.class));
dto.setFechaEvento(generateRandomDate());
		dto.setSalon(generateRandom(String.class));
		dto.setMateria(generateRandom(String.class));
		dto.setInformacion(generateRandom(String.class));
		
		UTIDTO result=uTIPersistence.createUTI(dto);
		
		Assert.assertNotNull(result);
		
		UTIEntity entity=em.find(UTIEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
Assert.assertEquals(parseDate(dto.getFechaEvento()), entity.getFechaEvento());	
		Assert.assertEquals(dto.getSalon(), entity.getSalon());
		Assert.assertEquals(dto.getMateria(), entity.getMateria());
		Assert.assertEquals(dto.getInformacion(), entity.getInformacion());
	}
	
	@Test
	public void getUTIsTest(){
		List<UTIDTO> list=uTIPersistence.getUTIs();
		Assert.assertEquals(list.size(), data.size());
        for(UTIDTO dto:list){
        	boolean found=false;
            for(UTIEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getUTITest(){
		UTIEntity entity=data.get(0);
		UTIDTO dto=uTIPersistence.getUTI(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getSalon(), dto.getSalon());
		Assert.assertEquals(entity.getMateria(), dto.getMateria());
		Assert.assertEquals(entity.getInformacion(), dto.getInformacion());
        
	}
	
	@Test
	public void deleteUTITest(){
		UTIEntity entity=data.get(0);
		uTIPersistence.deleteUTI(entity.getId());
        UTIEntity deleted=em.find(UTIEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateUTITest(){
		UTIEntity entity=data.get(0);
		
		UTIDTO dto=new UTIDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
dto.setFechaEvento(generateRandomDate());
		dto.setSalon(generateRandom(String.class));
		dto.setMateria(generateRandom(String.class));
		dto.setInformacion(generateRandom(String.class));
		
		
		uTIPersistence.updateUTI(dto);
		
		
		UTIEntity resp=em.find(UTIEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
Assert.assertEquals(parseDate(dto.getFechaEvento()), resp.getFechaEvento());
		Assert.assertEquals(dto.getSalon(), resp.getSalon());	
		Assert.assertEquals(dto.getMateria(), resp.getMateria());	
		Assert.assertEquals(dto.getInformacion(), resp.getInformacion());	
	}
	
	@Test
	public void getUTIPaginationTest(){
		//Page 1
		UTIPageDTO dto1=uTIPersistence.getUTIs(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        UTIPageDTO dto2=uTIPersistence.getUTIs(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(UTIDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(UTIEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(UTIDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(UTIEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}