/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.usuario.master.persistence.api;

import co.edu.uniandes.csw.SOFPA.usuario.master.persistence.entity.UsuariocontactoEntity;
import co.edu.uniandes.csw.SOFPA.contacto.logic.dto.ContactoDTO;
import co.edu.uniandes.csw.SOFPA.usuario.master.persistence.entity.UsuariorecursoEntity;
import co.edu.uniandes.csw.SOFPA.recurso.logic.dto.RecursoDTO;
import co.edu.uniandes.csw.SOFPA.usuario.master.logic.dto.UsuarioMasterDTO;
import java.util.List;

public interface _IUsuarioMasterPersistence {

	public UsuarioMasterDTO getUsuario(Long usuarioId);
	
	
    public UsuariocontactoEntity createUsuariocontactoEntity(UsuariocontactoEntity entity);
    public void deleteUsuariocontactoEntity(Long usuarioId, Long contactoId);
    public List<ContactoDTO> getUsuariocontactoEntityList(Long usuarioId);
    public UsuariorecursoEntity createUsuariorecursoEntity(UsuariorecursoEntity entity);
    public void deleteUsuariorecursoEntity(Long usuarioId, Long recursoId);
    public List<RecursoDTO> getUsuariorecursoEntityList(Long usuarioId);
   
  
}
