/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.sugerencia.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.SOFPA.sugerencia.logic.dto.SugerenciaDTO;
import co.edu.uniandes.csw.SOFPA.sugerencia.logic.dto.SugerenciaPageDTO;
import co.edu.uniandes.csw.SOFPA.sugerencia.persistence.api._ISugerenciaPersistence;
import co.edu.uniandes.csw.SOFPA.sugerencia.persistence.converter.SugerenciaConverter;
import co.edu.uniandes.csw.SOFPA.sugerencia.persistence.entity.SugerenciaEntity;

public abstract class _SugerenciaPersistence implements _ISugerenciaPersistence {

  	@PersistenceContext(unitName="ClinicaDeProblemasPU")
 
	protected EntityManager entityManager;
	
	public SugerenciaDTO createSugerencia(SugerenciaDTO sugerencia) {
		SugerenciaEntity entity=SugerenciaConverter.persistenceDTO2Entity(sugerencia);
		entityManager.persist(entity);
		return SugerenciaConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<SugerenciaDTO> getSugerencias() {
		Query q = entityManager.createQuery("select u from SugerenciaEntity u");
		return SugerenciaConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public SugerenciaPageDTO getSugerencias(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from SugerenciaEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from SugerenciaEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		SugerenciaPageDTO response = new SugerenciaPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(SugerenciaConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public SugerenciaDTO getSugerencia(Long id) {
		return SugerenciaConverter.entity2PersistenceDTO(entityManager.find(SugerenciaEntity.class, id));
	}

	public void deleteSugerencia(Long id) {
		SugerenciaEntity entity=entityManager.find(SugerenciaEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateSugerencia(SugerenciaDTO detail) {
		SugerenciaEntity entity=entityManager.merge(SugerenciaConverter.persistenceDTO2Entity(detail));
		SugerenciaConverter.entity2PersistenceDTO(entity);
	}

}