/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.contacto.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.SOFPA.contacto.logic.dto.ContactoDTO;
import co.edu.uniandes.csw.SOFPA.contacto.logic.dto.ContactoPageDTO;
import co.edu.uniandes.csw.SOFPA.contacto.persistence.api._IContactoPersistence;
import co.edu.uniandes.csw.SOFPA.contacto.persistence.converter.ContactoConverter;
import co.edu.uniandes.csw.SOFPA.contacto.persistence.entity.ContactoEntity;

public abstract class _ContactoPersistence implements _IContactoPersistence {

  	@PersistenceContext(unitName="ClinicaDeProblemasPU")
 
	protected EntityManager entityManager;
	
	public ContactoDTO createContacto(ContactoDTO contacto) {
		ContactoEntity entity=ContactoConverter.persistenceDTO2Entity(contacto);
		entityManager.persist(entity);
		return ContactoConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<ContactoDTO> getContactos() {
		Query q = entityManager.createQuery("select u from ContactoEntity u");
		return ContactoConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public ContactoPageDTO getContactos(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from ContactoEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from ContactoEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		ContactoPageDTO response = new ContactoPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(ContactoConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public ContactoDTO getContacto(Long id) {
		return ContactoConverter.entity2PersistenceDTO(entityManager.find(ContactoEntity.class, id));
	}

	public void deleteContacto(Long id) {
		ContactoEntity entity=entityManager.find(ContactoEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateContacto(ContactoDTO detail) {
		ContactoEntity entity=entityManager.merge(ContactoConverter.persistenceDTO2Entity(detail));
		ContactoConverter.entity2PersistenceDTO(entity);
	}

}