/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.contacto.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.SOFPA.contacto.logic.dto.ContactoDTO;
import co.edu.uniandes.csw.SOFPA.contacto.persistence.entity.ContactoEntity;

public abstract class _ContactoConverter {

	public static ContactoDTO entity2PersistenceDTO(ContactoEntity entity){
		if (entity != null) {
			ContactoDTO dto = new ContactoDTO();
					dto.setName(entity.getName());
					dto.setId(entity.getId());
					dto.setObsevacion(entity.getObsevacion());
					dto.setTema(entity.getTema());
					dto.setLogin(entity.getLogin());
					dto.setCodigo(entity.getCodigo());
					dto.setCarrera(entity.getCarrera());
			return dto;
		}else{
			return null;
		}
	}
	
	public static ContactoEntity persistenceDTO2Entity(ContactoDTO dto){
		if(dto!=null){
			ContactoEntity entity=new ContactoEntity();
					entity.setName(dto.getName());
			
					entity.setId(dto.getId());
			
					entity.setObsevacion(dto.getObsevacion());
			
					entity.setTema(dto.getTema());
			
					entity.setLogin(dto.getLogin());
			
					entity.setCodigo(dto.getCodigo());
			
					entity.setCarrera(dto.getCarrera());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<ContactoDTO> entity2PersistenceDTOList(List<ContactoEntity> entities){
		List<ContactoDTO> dtos=new ArrayList<ContactoDTO>();
		for(ContactoEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<ContactoEntity> persistenceDTO2EntityList(List<ContactoDTO> dtos){
		List<ContactoEntity> entities=new ArrayList<ContactoEntity>();
		for(ContactoDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}