/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.uti.master.logic.dto;

import co.edu.uniandes.csw.SOFPA.opinion.logic.dto.OpinionDTO;
import co.edu.uniandes.csw.SOFPA.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.SOFPA.uti.logic.dto.UTIDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _UTIMasterDTO {

 
    protected UTIDTO utiEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public UTIDTO getUTIEntity() {
        return utiEntity;
    }

    public void setUTIEntity(UTIDTO utiEntity) {
        this.utiEntity = utiEntity;
    }
    
    public List<OpinionDTO> createopinion;
    public List<OpinionDTO> updateopinion;
    public List<OpinionDTO> deleteopinion;
    public List<OpinionDTO> listopinion;	
    public List<UsuarioDTO> createusuario;
    public List<UsuarioDTO> updateusuario;
    public List<UsuarioDTO> deleteusuario;
    public List<UsuarioDTO> listusuario;	
	
	
	
    public List<OpinionDTO> getCreateopinion(){ return createopinion; };
    public void setCreateopinion(List<OpinionDTO> createopinion){ this.createopinion=createopinion; };
    public List<OpinionDTO> getUpdateopinion(){ return updateopinion; };
    public void setUpdateopinion(List<OpinionDTO> updateopinion){ this.updateopinion=updateopinion; };
    public List<OpinionDTO> getDeleteopinion(){ return deleteopinion; };
    public void setDeleteopinion(List<OpinionDTO> deleteopinion){ this.deleteopinion=deleteopinion; };
    public List<OpinionDTO> getListopinion(){ return listopinion; };
    public void setListopinion(List<OpinionDTO> listopinion){ this.listopinion=listopinion; };	
    public List<UsuarioDTO> getCreateusuario(){ return createusuario; };
    public void setCreateusuario(List<UsuarioDTO> createusuario){ this.createusuario=createusuario; };
    public List<UsuarioDTO> getUpdateusuario(){ return updateusuario; };
    public void setUpdateusuario(List<UsuarioDTO> updateusuario){ this.updateusuario=updateusuario; };
    public List<UsuarioDTO> getDeleteusuario(){ return deleteusuario; };
    public void setDeleteusuario(List<UsuarioDTO> deleteusuario){ this.deleteusuario=deleteusuario; };
    public List<UsuarioDTO> getListusuario(){ return listusuario; };
    public void setListusuario(List<UsuarioDTO> listusuario){ this.listusuario=listusuario; };	
	
	
}

