/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.uti.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.SOFPA.uti.logic.dto.UTIPageDTO;
import co.edu.uniandes.csw.SOFPA.uti.logic.dto.UTIDTO;
import co.edu.uniandes.csw.SOFPA.uti.logic.api.IUTILogicService;
import co.edu.uniandes.csw.SOFPA.uti.persistence.UTIPersistence;
import co.edu.uniandes.csw.SOFPA.uti.persistence.api.IUTIPersistence;
import co.edu.uniandes.csw.SOFPA.uti.persistence.entity.UTIEntity;
import co.edu.uniandes.csw.SOFPA.uti.persistence.converter.UTIConverter;
import static co.edu.uniandes.csw.SOFPA.util._TestUtil.*;

@RunWith(Arquillian.class)
public class UTILogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(UTILogicService.class.getPackage())
				.addPackage(IUTILogicService.class.getPackage())
				.addPackage(UTIPersistence.class.getPackage())
				.addPackage(UTIEntity.class.getPackage())
				.addPackage(IUTIPersistence.class.getPackage())
                .addPackage(UTIDTO.class.getPackage())
                .addPackage(UTIConverter.class.getPackage())
                .addPackage(UTIEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IUTILogicService uTILogicService;
	
	@Inject
	private IUTIPersistence uTIPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<UTIDTO> dtos=uTIPersistence.getUTIs();
		for(UTIDTO dto:dtos){
			uTIPersistence.deleteUTI(dto.getId());
		}
	}

	private List<UTIDTO> data=new ArrayList<UTIDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			UTIDTO pdto=new UTIDTO();
			pdto.setName(generateRandom(String.class));
			pdto.setFechaEvento(generateRandomDate());
			pdto.setSalon(generateRandom(String.class));
			pdto.setMateria(generateRandom(String.class));
			pdto.setInformacion(generateRandom(String.class));
			pdto=uTIPersistence.createUTI(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createUTITest(){
		UTIDTO ldto=new UTIDTO();
		ldto.setName(generateRandom(String.class));
		ldto.setFechaEvento(generateRandomDate());
		ldto.setSalon(generateRandom(String.class));
		ldto.setMateria(generateRandom(String.class));
		ldto.setInformacion(generateRandom(String.class));
		
		
		UTIDTO result=uTILogicService.createUTI(ldto);
		
		Assert.assertNotNull(result);
		
		UTIDTO pdto=uTIPersistence.getUTI(result.getId());
		
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getFechaEvento(), pdto.getFechaEvento());	
		Assert.assertEquals(ldto.getSalon(), pdto.getSalon());	
		Assert.assertEquals(ldto.getMateria(), pdto.getMateria());	
		Assert.assertEquals(ldto.getInformacion(), pdto.getInformacion());	
	}
	
	@Test
	public void getUTIsTest(){
		List<UTIDTO> list=uTILogicService.getUTIs();
		Assert.assertEquals(list.size(), data.size());
        for(UTIDTO ldto:list){
        	boolean found=false;
            for(UTIDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getUTITest(){
		UTIDTO pdto=data.get(0);
		UTIDTO ldto=uTILogicService.getUTI(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getFechaEvento(), ldto.getFechaEvento());
		Assert.assertEquals(pdto.getSalon(), ldto.getSalon());
		Assert.assertEquals(pdto.getMateria(), ldto.getMateria());
		Assert.assertEquals(pdto.getInformacion(), ldto.getInformacion());
        
	}
	
	@Test
	public void deleteUTITest(){
		UTIDTO pdto=data.get(0);
		uTILogicService.deleteUTI(pdto.getId());
        UTIDTO deleted=uTIPersistence.getUTI(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateUTITest(){
		UTIDTO pdto=data.get(0);
		
		UTIDTO ldto=new UTIDTO();
		ldto.setId(pdto.getId());
		ldto.setName(generateRandom(String.class));
		ldto.setFechaEvento(generateRandomDate());
		ldto.setSalon(generateRandom(String.class));
		ldto.setMateria(generateRandom(String.class));
		ldto.setInformacion(generateRandom(String.class));
		
		
		uTILogicService.updateUTI(ldto);
		
		
		UTIDTO resp=uTIPersistence.getUTI(pdto.getId());
		
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getFechaEvento(), resp.getFechaEvento());	
		Assert.assertEquals(ldto.getSalon(), resp.getSalon());	
		Assert.assertEquals(ldto.getMateria(), resp.getMateria());	
		Assert.assertEquals(ldto.getInformacion(), resp.getInformacion());	
	}
	
	@Test
	public void getUTIPaginationTest(){
		
		UTIPageDTO dto1=uTILogicService.getUTIs(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		UTIPageDTO dto2=uTILogicService.getUTIs(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(UTIDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(UTIDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(UTIDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(UTIDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        UTIPageDTO dto3=uTILogicService.getUTIs(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(UTIDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(UTIDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}