/* ========================================================================
 * Copyright 2014 SOFPA
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SOFPA

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.SOFPA.uti.master.persistence.entity;

import co.edu.uniandes.csw.SOFPA.usuario.persistence.entity.UsuarioEntity;
import co.edu.uniandes.csw.SOFPA.uti.persistence.entity.UTIEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(UTIusuarioEntityId.class)
@NamedQueries({
    @NamedQuery(name = "UTIusuarioEntity.getByMasterId", query = "SELECT  u FROM UTIusuarioEntity u WHERE u.uTIId=:uTIId"),
    @NamedQuery(name = "UTIusuarioEntity.deleteUTIusuarioEntity", query = "DELETE FROM UTIusuarioEntity u WHERE u.uTIId=:uTIId and  u.usuarioId=:usuarioId")
})
public class UTIusuarioEntity implements Serializable {

    @Id
    @Column(name = "uTIId")
    private Long uTIId;
    @Id
    @Column(name = "usuarioId")
    private Long usuarioId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "uTIId", referencedColumnName = "id")
    @JoinFetch
    private UsuarioEntity uTIIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "usuarioId", referencedColumnName = "id")
    @JoinFetch
    private UsuarioEntity usuarioIdEntity; 

    public UTIusuarioEntity() {
    }

    public UTIusuarioEntity(Long uTIId, Long usuarioId) {
        this.uTIId =uTIId;
        this.usuarioId = usuarioId;
    }

    public Long getUTIId() {
        return uTIId;
    }

    public void setUTIId(Long uTIId) {
        this.uTIId = uTIId;
    }

    public Long getUsuarioId() {
        return usuarioId;
    }

    public void setUsuarioId(Long usuarioId) {
        this.usuarioId = usuarioId;
    }

    public UsuarioEntity getUTIIdEntity() {
        return uTIIdEntity;
    }

    public void setUTIIdEntity(UsuarioEntity uTIIdEntity) {
        this.uTIIdEntity = uTIIdEntity;
    }

    public UsuarioEntity getUsuarioIdEntity() {
        return usuarioIdEntity;
    }

    public void setUsuarioIdEntity(UsuarioEntity usuarioIdEntity) {
        this.usuarioIdEntity = usuarioIdEntity;
    }

}
